{
 "title": "margin crypto exporter",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "v_vps_name", "label": "vps_name", "query": { "query": "label_values(vps_name)" } },
   {
    "name": "v_exchange",
    "label": "Exchange",
    "query": {
     "query": "label_values({vps_name=~\"$v_vps_name\"},exchange)"
    }
   },
   {
    "name": "v_pair",
    "label": "Pair:",
    "query": {
     "query": "label_values({exchange=~\"$v_exchange\"},pair)"
    }
   },
   {
    "name": "v_currency",
    "label": "currency",
    "query": {
     "query": "label_values({exchange=~\"$v_exchange\"}, currency)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Consolidated asset valuation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Assets",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "margin_balance_usd{currency=~\"$v_currency\",exchange=~\"$v_exchange\"}",
     "legendFormat": "{{currency}} {{exchange}}"
    },
    {
     "expr": "sum(margin_balance_usd{currency=~\"$v_currency\",exchange=~\"$v_exchange\"})",
     "legendFormat": "USD"
    }
   ]
  },
  {
   "title": "VPS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "$v_vps_name",
     "type": "graph",
     "gridPos": { "h": 10, "w": 23, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "percentunit", "label": "cpu" }
     ],
     "targets": [
      {
       "expr": "margin_vps_cpu{vps_name=~\"$v_vps_name\"}",
       "legendFormat": "cpu"
      },
      {
       "expr": "margin_vps_memory{vps_name=~\"$v_vps_name\"}",
       "legendFormat": "memory"
      }
     ]
    }
   ]
  },
  {
   "title": "Margin",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cycle count",
     "type": "stat",
     "gridPos": { "h": 8, "w": 2, "x": 0, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "margin_cycle_count{pair=~\"$v_pair\",exchange=~\"$v_exchange\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "margin_buy_count{pair=~\"$v_pair\",exchange=~\"$v_exchange\"}",
       "legendFormat": "Buy"
      },
      {
       "expr": "margin_sell_count{pair=~\"$v_pair\",exchange=~\"$v_exchange\"}",
       "legendFormat": "Sell"
      }
     ]
    },
    {
     "title": "RATE",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 2, "y": 13 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "margin_last_rate{pair=~\"$v_pair\",exchange=~\"$v_exchange\",vps_name=~\"$v_vps_name\"}",
       "legendFormat": "value"
      }
     ]
    },
    {
     "title": "--> $v_pair",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
     "yaxes": [
      { "format": "currencyBTC" }
     ],
     "targets": [
      {
       "expr": "margin_f_balance{pair=~\"$v_pair\",exchange=~\"$v_exchange\",vps_name=~\"$v_vps_name\"}",
       "legendFormat": "Amount"
      },
      {
       "expr": "margin_f_profit{pair=~\"$v_pair\",exchange=~\"$v_exchange\",vps_name=~\"$v_vps_name\"}",
       "legendFormat": "Profit"
      }
     ]
    },
    {
     "title": "$v_pair<--",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 14, "y": 13 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "margin_s_balance{pair=~\"$v_pair\",exchange=~\"$v_exchange\",vps_name=~\"$v_vps_name\",vps_name=~\"$v_vps_name\"}",
       "legendFormat": "Amount"
      },
      {
       "expr": "margin_s_profit{pair=~\"$v_pair\",exchange=~\"$v_exchange\",vps_name=~\"$v_vps_name\",vps_name=~\"$v_vps_name\"}",
       "legendFormat": "Profit"
      },
      {
       "expr": "margin_sum_profit{pair=~\"$v_pair\",exchange=~\"$v_exchange\",vps_name=~\"$v_vps_name\",vps_name=~\"$v_vps_name\"}",
       "legendFormat": "Sum profit by last rate"
      }
     ]
    },
    {
     "title": "Interest for all time",
     "type": "stat",
     "gridPos": { "h": 16, "w": 4, "x": 20, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "margin_buy_interest{pair=~\"$v_pair\",exchange=~\"$v_exchange\",vps_name=~\"$v_vps_name\"}",
       "legendFormat": "Buy interest"
      },
      {
       "expr": "margin_sell_interest{pair=~\"$v_pair\",exchange=~\"$v_exchange\",vps_name=~\"$v_vps_name\"}",
       "legendFormat": "Sell interest"
      },
      {
       "expr": "margin_buy_time{pair=~\"$v_pair\",exchange=~\"$v_exchange\",vps_name=~\"$v_vps_name\"}",
       "legendFormat": "Buy time"
      },
      {
       "expr": "margin_sell_time{pair=~\"$v_pair\",exchange=~\"$v_exchange\",vps_name=~\"$v_vps_name\"}",
       "legendFormat": "Sell time"
      },
      {
       "expr": "86400 * margin_buy_interest{pair=~\"$v_pair\",exchange=~\"$v_exchange\",vps_name=~\"$v_vps_name\"} / margin_buy_time{pair=~\"$v_pair\",exchange=~\"$v_exchange\",vps_name=~\"$v_vps_name\"}",
       "legendFormat": "Avg Buy interest for 24h"
      },
      {
       "expr": "86400 * margin_sell_interest{pair=~\"$v_pair\",exchange=~\"$v_exchange\",vps_name=~\"$v_vps_name\"} / margin_sell_time{pair=~\"$v_pair\",exchange=~\"$v_exchange\",vps_name=~\"$v_vps_name\"}",
       "legendFormat": "Avg Sell interest for 24h"
      },
      {
       "expr": "31536000 * margin_buy_interest{pair=~\"$v_pair\",exchange=~\"$v_exchange\",vps_name=~\"$v_vps_name\"} / margin_buy_time{pair=~\"$v_pair\",exchange=~\"$v_exchange\",vps_name=~\"$v_vps_name\"}",
       "legendFormat": "Forecast APY Buy"
      },
      {
       "expr": "31536000 * margin_sell_interest{pair=~\"$v_pair\",exchange=~\"$v_exchange\",vps_name=~\"$v_vps_name\"} / margin_sell_time{pair=~\"$v_pair\",exchange=~\"$v_exchange\",vps_name=~\"$v_vps_name\"}",
       "legendFormat": "Forecast APY Sell"
      }
     ]
    },
    {
     "title": "Summary amount ($v_pair<--)",
     "type": "graph",
     "description": "Total amount for both currency by last rate",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "margin_balance{pair=~\"$v_pair\",exchange=~\"$v_exchange\",vps_name=~\"$v_vps_name\"}",
       "legendFormat": "value"
      }
     ]
    }
   ]
  }
 ]
}