[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "martin-binance"
authors = [{name = "Jerry Fedorenko", email = "jerry.fedorenko@yahoo.com"}]
readme = "README.md"
license = {file = "LICENSE"}
classifiers=["Programming Language :: Python :: 3",
             "Development Status :: 5 - Production/Stable",
             "License :: OSI Approved :: MIT License",
             "Operating System :: Unix",
             "Operating System :: Microsoft :: Windows",
             "Operating System :: MacOS"]
dynamic = ["version", "description"]
requires-python = ">=3.8"

dependencies = [
    "exchanges-wrapper==1.2.7.post7",
    "margin-strategy-sdk==0.0.11",
    "aiohttp==3.8.1",
    "grpcio==1.48.1",
    "grpcio-tools==1.48.1",
    "jsonpickle==2.2.0",
    "psutil==5.9.1",
    "requests==2.28.1",
    "simplejson==3.17.6",
    "toml==0.10.2",
    "libtmux==0.14.0",
    "colorama==0.4.5",
    "prometheus-client==0.14.1"
]

[tool.flit.module]
name = "martin_binance"

[project.urls]
Source = "https://github.com/DogsTailFarmer/martin-binance"
