# Parameters for Binance API Server /binance_srv.py
# Copyright © 2021 Jerry Fedorenko aka VM

[Path]
log_path = './log/'

[endpoint]
api = 'https://api.binance.com'
ws = 'wss://stream.binance.com:9443'

[endpoint_test]
api = 'https://testnet.binance.vision'
ws = 'wss://testnet.binance.vision/ws'

[[accounts]]
name = 'Demo - Binance'
api_key = '*********** Place API key there ************'
api_secret = '*********** Place secret API key there ************'
test_net = true

[[accounts]]
name = 'Binance'
api_key = '*********** Place API key there ************'
api_secret = '*********** Place secret API key there ************'
test_net = false